"""Stage 1: domain model

Revision ID: b48094db5775
Revises: 
Create Date: 2026-08-01 11:40:46.049995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b48094db5775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('sim_day', sa.Integer(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('ix_agent_decision_agent_day', 'agent_decisions', ['agent_name', 'sim_day'], unique=False)
    op.create_index(op.f('ix_agent_decisions_agent_name'), 'agent_decisions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_decisions_sim_day'), 'agent_decisions', ['sim_day'], unique=False)
    op.create_table('drugs',
    sa.Column('drug_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('atc_code', sa.String(length=16), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=False),
    sa.Column('requires_cold_chain', sa.Boolean(), nullable=False),
    sa.Column('temp_min_c', sa.Float(), nullable=True),
    sa.Column('temp_max_c', sa.Float(), nullable=True),
    sa.Column('is_controlled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT requires_cold_chain OR (temp_min_c IS NOT NULL AND temp_max_c IS NOT NULL)', name='ck_drug_cold_chain_has_range'),
    sa.CheckConstraint('shelf_life_days > 0', name='ck_drug_shelf_life_positive'),
    sa.CheckConstraint('temp_min_c IS NULL OR temp_max_c IS NULL OR temp_min_c < temp_max_c', name='ck_drug_temp_range_ordered'),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.Enum('MANUFACTURER', 'WAREHOUSE', 'DISTRIBUTOR', 'PHARMACY', 'HOSPITAL', name='node_type'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('storage_capacity', sa.Integer(), nullable=False),
    sa.Column('has_cold_storage', sa.Boolean(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name='ck_node_lat_range'),
    sa.CheckConstraint('lon BETWEEN -180 AND 180', name='ck_node_lon_range'),
    sa.CheckConstraint('storage_capacity >= 0', name='ck_node_capacity_nonneg'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_nodes_node_type'), 'nodes', ['node_type'], unique=False)
    op.create_table('batches',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('drug_id', sa.String(length=32), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=32), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_fingerprint', sa.String(length=64), nullable=False),
    sa.CheckConstraint('char_length(batch_fingerprint) = 64', name='ck_batch_fingerprint_sha256'),
    sa.CheckConstraint('expiry_date > mfg_date', name='ck_batch_expiry_after_mfg'),
    sa.CheckConstraint('quantity >= 0', name='ck_batch_quantity_nonneg'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_drug_id'), 'batches', ['drug_id'], unique=False)
    op.create_index(op.f('ix_batches_expiry_date'), 'batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_batches_manufacturer_id'), 'batches', ['manufacturer_id'], unique=False)
    op.create_table('demand_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('drug_id', sa.String(length=32), nullable=False),
    sa.Column('sim_day', sa.Integer(), nullable=False),
    sa.Column('quantity_demanded', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_demanded >= 0', name='ck_demand_demanded_nonneg'),
    sa.CheckConstraint('quantity_fulfilled <= quantity_demanded', name='ck_demand_fulfilled_lte_demanded'),
    sa.CheckConstraint('quantity_fulfilled >= 0', name='ck_demand_fulfilled_nonneg'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'drug_id', 'sim_day', name='uq_demand_node_drug_day')
    )
    op.create_index('ix_demand_node_drug_day', 'demand_records', ['node_id', 'drug_id', 'sim_day'], unique=False)
    op.create_table('inventory_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('sim_day', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_qty_nonneg'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'batch_id', 'sim_day', name='uq_inventory_node_batch_day')
    )
    op.create_index('ix_inventory_node_day', 'inventory_records', ['node_id', 'sim_day'], unique=False)
    op.create_table('shipments',
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('from_node', sa.String(length=32), nullable=False),
    sa.Column('to_node', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dispatch_day', sa.Integer(), nullable=False),
    sa.Column('eta_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='shipment_status'), nullable=False),
    sa.Column('temp_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('eta_day >= dispatch_day', name='ck_shipment_eta_after_dispatch'),
    sa.CheckConstraint('from_node <> to_node', name='ck_shipment_distinct_endpoints'),
    sa.CheckConstraint('quantity > 0', name='ck_shipment_quantity_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['from_node'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['to_node'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_index(op.f('ix_shipments_batch_id'), 'shipments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_batch_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_inventory_node_day', table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index('ix_demand_node_drug_day', table_name='demand_records')
    op.drop_table('demand_records')
    op.drop_index(op.f('ix_batches_manufacturer_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_expiry_date'), table_name='batches')
    op.drop_index(op.f('ix_batches_drug_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_nodes_node_type'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_agent_decisions_sim_day'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_agent_name'), table_name='agent_decisions')
    op.drop_index('ix_agent_decision_agent_day', table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
